### ISSUE TITLE
Remove deprecated code that can be removed with Neos 6.0

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-development-collection#3137]
## Todos

- [x] Add `getIconUri()` & `getDescription()` to `AssetSourceInterface` (#3211)
- [x] Remove default prototype generator (#3210)
- [x] Adjust deprecated notices for next release (#3207)
- [x] Rename TYPO3CR to ContentRepository (#3188)
- [x] Fix deprecations in PHP Node API (#3187) (done but needs to be backported to 4.3 #3194)
- [x] Remove deprecated Fusion prototype usage from core
   - [x] #3198 Array › Join
   - [x] #3202 Collection › Loop
   - [x] #3203  Replace test function names to map prototype name in Map test
   - [x] #3200 RawArray › DataStructure
   - [x] #3201 Replace TS in comments with Fusion 
- [x] ~Remove deprecated Fusion prototypes (?)~ (will be removed in 8.0)

Many stuff can be removed with Neos Version 6.0. You can get an overview by searching for `deprecated`: https://github.com/neos/neos-development-collection/search?q=deprecated

And in some, we have to check history, if no [version number] is mentioned :) This can require that we go through git history for that single file when in doubt, so we do not remove wrong stuff by accident :)

**Comment by bwaidelich** [comment]
Also, don't forget deprecated Fusion Prototypes: https://github.com/neos/fusion/search?q=deprecated

**Comment by bwaidelich** [comment]
I talked to @skurfuerst regarding the NodeInterface deprecations and this is our suggestion:
* Reword the deprecation message in the class doc comment (i.e. delete the "REMOVED in version 6.0" etc)
* For deprecated methods with a replacement (e.g. `getDepth()`):
  * Don't remove the method but keep the deprecation annotation
  * Remove any `@api` annotation from the method
* For deprecated methods without replacement (e.g. `getContextPath()`):
  * Don't remove the method
  * replace the `@deprecated` annotation by some comment that states that this method might be removed in the future for performance reasons. For `contextPath` we should explicitly mention that one should not rely on the inner structure of this value

**Comment by bwaidelich** [comment]
@jonnitto did you already create a PR for the deprecated fusion prototypes that we can link in the todo list above?

**Comment by bwaidelich** [comment]
@jonnitto Thanks for taking care! I think I just merged the last PR assigned to this issue. Can we close it?  Whoop whoop
