### ISSUE TITLE
EPIC: Performance improvements

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4388]
This issue should serve as an epic for performance related improvements for Neos 9.0

- [x] inline editing - #4387
  - Currently when inline-editing a text in the Neos content module, changes are sent to the server during typing leading to sometimes multiple `NodePropertiesWereSet` properties per second!
- [ ] Flow Query - #4205
  - Especially the `find` operation is really slow currently because a CTE has to go through _all_ nodes 
- [x] Rework CatchUp mechanism - #4746
- [x] Don't rebase the user workspace on Login if not required #4728
- [ ] Implement subgraph with runtime caches correctly
  - [x] https://github.com/neos/neos-development-collection/pull/4763
- [ ] ES CR DBAL Adapter https://github.com/neos/neos-development-collection/issues/4818
- [ ] https://github.com/neos/neos-development-collection/issues/5264
- [x] https://github.com/neos/neos-development-collection/issues/5303
- [ ] https://github.com/neos/neos-development-collection/pull/5718

**Comment by mhsdesign** [comment]
Also our `ContentSubgraphWithRuntimeCaches` can be improved a lot as it mostly doenst cache or read from the cache.

I found a tiny improvement here already: https://github.com/neos/contentrepository-development-collection/pull/129

**Comment by mhsdesign** [comment]
discussions we had on the 4.7.25. regarding neos 9 cr optimisation:

-   explict workspace creation screen
    -   the user will see that the login worked and see neos fast
    -   if the creation takes longer - because the fork might be expensive for a big site - we can offer a progress bar and the user will not terminate the connection which might be a cause for inconsistencies?
    -   feature: in a later step we can also offer to view live in read only
-   rule out that connection termination from the client can abort a long catchup
-   dashboard for subscription state and offer to update subscription if out of sync
    -   currently the catchup might be triggered if a command could be applied sucessfully elsewhere (in another workspace)
    -   but if the workspace is out of sync futher commands on that workspace will fail with an expected version exception -> catch and opt to redirect to new module?
    -   todo handle mismatch for importers?
-   debug slow queries [neos.io](http://neos.io/) (2s) probably subtree -> investigate to use anchor paths
-   add time logging for catchup!!! to find out that catchups are slow because of 3rd party hooks
-   optimise our catchup hooks
-   Fastforward content stream idea? For single workspace usecase (edit publish)
- for custom importers the ContentRepositoryMaintainer must learn to update subscriptions at the start?
- noop when set properties are already the ones? (especially fun with null and unset case)
  - currently a lot events are emitted
  - -> reopens discussion with redisabling node
- if we see more connections dying (and the php process) we must ensure that cr->handle also only makes ONE event store commit (and transaction)

**Comment by skurfuerst** [comment]
Discussion with @mhsdesign regarding Performance and Neos 9.1 - how to improve it for Neos.io as an example:

While analyzing Neos.io, we found the following:
- Login is slow
- publishing is slow.

We checked the database:

- 78 content streams active, but only 4 have changes
- !PRIO1! it would be VERY useful to only have content streams active (with hierarchy relations) if they have changes.
  - -> this reduces the data amount tremendously, and thus all operations with the data will be faster.
  - Forking (from UI side) should only happen when actually changing things the 1st time in the UI
  - **implemented by https://github.com/neos/neos-development-collection/pull/5718**
- !PRIO2! we can additionally POOL unused content streams, so that in one of the unused content streams can be claimed when forking.
  - this speeds up the fork
  - the content stream pool should be updated transparently always in sync with the live content stream (today: `UPDATE ...hierarchyrelation WHERE contentstream=live` -> future: `UPDATE ...hierarchyrelation WHERE contentstream IN (live, pool-1, pool-2)` (synchronously!!)
- Filling up the unused content stream pool can happen asynchronously (for big instances), via cron -> user would see an error if pool is exhausted, and can maybe trigger "auffüllen"
  - for small instances we might "fill up" the pool automatically synchronously.
- !PRIO3! Event compraction on publish

- !PRIO-later! #5264 
- !PRIO-later! #3855 

**We do NOT need to change the current events for this as far as we see it.**

- We need additional performance monitoring in CR core to finally know what is slow (and how much) @skurfuerst will work on this

**Comment by skurfuerst** [comment]
Related: https://github.com/neos/neos-development-collection/pull/5718
