### ISSUE TITLE
Code deprecations

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4498]
- [x] https://github.com/neos/neos-development-collection/pull/4496
- [x] https://github.com/neos/neos-development-collection/pull/4544
- [x] https://github.com/neos/neos-development-collection/pull/4537
- [x] https://github.com/neos/neos-development-collection/issues/4552
- [x] https://github.com/neos/neos-development-collection/issues/3771
- [x] https://github.com/neos/neos-development-collection/pull/4537
- [x] https://github.com/neos/neos-development-collection/pull/4883

related: https://github.com/neos/neos-development-collection/issues/4478

... if you find further cases feel free to extend the list
