### ISSUE TITLE
TASK: Check and fix Neos:NodeTypes packages

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-development-collection#4705]
- Check Neos.NodeTypes packages:
  - after removal of fusion prototypes (#4537)
  - refactoring of Neos.Neos:Page (#4654)
  - refactoring of menu prototypes (#4623, #4671)
  - remove fluid rendering

Packages:

- [x] Neos.NodeTypes
  - [x] Adjust to refactored Neos.Neos:Page (#4704)
  - [x] Neos.NodeTypes:Headline (#4706)
  - [x] Neos.NodeTypes:Text (#4706)
  - [x] Neos.NodeTypes:Image
  - [x] Neos.NodeTypes:TextWithImage
- [x] Neos.NodeTypes.AssetList (#4706)
- [x] Neos.NodeTypes.ColumnLayouts (#4706)
- [x] Neos.NodeTypes.ContentReferences (#4706)
- [x] Neos.NodeTypes.Form
- [x] Neos.NodeTypes.Html (#4670)
- [x] Neos.NodeTypes.Navigation

**Comment by ahaeslich** [comment]
@mficzel looking into this I have found that `Neos.NodeTypes.Form:Form` uses the fluid based form implementation instead of `Neos.Fusion.Form`. Should we migrate this NodeType to use the new package?

**Comment by ahaeslich** [comment]
Besides cleaning up those prototypes: Should we also cleanup the migrations in https://github.com/neos/neos-development-collection/tree/9.0/Neos.NodeTypes/Migrations as we have done for other packages in Neos 9.

Maybe @kdambekalns , @Sebobo and @mficzel have an idea about this.

**Comment by mficzel** [comment]
@ahaeslich i see not much hope for Neos.NodeTypes.Form:Form and no point in updating it. We should define new "default" nodetypes (without rendering) in future once we have a working concept of nested properties in the inspector.
