### ISSUE TITLE
Workspace/Publishing improvements

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4726]
Epic for issues related to the UX with workspace handling and publishing

- [x] Refer to `WorkspaceName` instead of `ContentStreamId` in commands (#4694)
- [x] User Workspace is null if first login to the site happens via "/neos/switch/to/..." (#4401)
- [x] Indicator for the Workspace state (https://github.com/neos/neos-ui/issues/3803)
- [x] Don't rebase the user workspace on Login if not required (#4728)
- [ ] 9.0 New workspace module (#4255)
- [x] Running ./flow structureadjustments:fix doesn't mark workspaces as outdated (#4508)
- [ ] Odd things about (user) workspaces (#4566)
