### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4776]
This issue should serve as an epic for documentation related improvements for Neos 9.0

- [ ] Update docs.neos.io content #4059 version 1
- [ ] Reupdate new Neos 9 docs.neos.io things that changed lately
  - [ ] no blocking anymore
  - [ ] workspace instead of cs id
  - [ ] node name is not part of hierarchy relation table
  - [ ] hidden state finder and projection gone and we have subtree tags
- [ ] https://github.com/neos/neos-development-collection/issues/4314
  - [ ] https://github.com/neos/neos-development-collection/issues/4312
- [ ] https://github.com/neos/neos-development-collection/issues/4907
- [ ] https://github.com/neos/neos-development-collection/issues/4539
- [ ] https://github.com/neos/neos-development-collection/issues/4386
