### ISSUE TITLE
Developer Experience

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#4777]
This issue should serve as an epic for DX related improvements for Neos 9.0

- [x] High level cr:import / Read site:import #4448
- [x] ~Handle Exceptions in Projections #3854~ will be mostly solved with #4746
- [x] Node properties vs references confusion #4549
- [ ] Cleanup duplicate php class names across project #4341
- [x] Add context property to `ContentStreamWasForked` events #4758
- [x] Add correlation and causation ids to events #3887
- [x] Command Hooks #5335
- [x] Rework CatchUp mechanism #4746
