### ISSUE TITLE
Workspace aware `ContentGraph` / `Node` followup

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5038]
Followup for https://github.com/neos/neos-development-collection/pull/5028

- [x] dont access foreign projections via sql: https://github.com/neos/neos-development-collection/pull/5028#discussion_r1590607479
  - [x] #5096
- [ ] avoid workspace finder being used in command handling `CommandHandlingDependencies::getWorkspaceFinder` (and `getContentStreamFinder`) -> obsolete now that its one projection
- [ ] clearly document and explain subgraph instance caching and memory cache and lifetime -> at the moment we disabled all caches and moved the subgraph cache to the cr registry
  -> https://github.com/neos/neos-development-collection/issues/5039
  - [ ] or even refactor this behaviour? https://github.com/neos/neos-development-collection/pull/5028#discussion_r1590801343 
- [ ] make content graph projection first level citizen and remove `ContentGraphFinder::getByWorkspaceNameAndContentStreamId` by passing the content graph factory directly to the `CommandHandlingDependencies` -> will be fixe via #5272
  - [x] maybe remove the `ContentGraphFinder` thing or rename it?
- [ ] remove or 'fix' `ContentGraphInterface::countNodes -> will be moved out of the content graph with #5272
  - `iExpectTheSubgraphProjectionToConsistOfExactlyNodes` is a dub of `iExpectTheGraphProjectionToConsistOfExactlyNodes` -> nope one is for subgraph and other is globally
  - see comment https://github.com/neos/neos-development-collection/pull/5028#discussion_r1590865439
- [ ] remove reflection in tests https://github.com/neos/neos-development-collection/pull/5028#discussion_r1591946339 and https://github.com/neos/neos-development-collection/issues/4634
- [ ] remove cs id from tests https://github.com/neos/neos-development-collection/issues/5034
- [ ] requireContentStreamDoes not exist constraint is not covered by tests: https://github.com/neos/neos-development-collection/pull/5028#issuecomment-2105143916
- [x] discuss `getContentGraph` nullable or throwing exception?
   -> the expectation is that the workspace _does_ exist and it would just make the code using it more complex. Also there is likely no fallback option available meaning we will mostly throw an exception again, so this might as well be the default.
- [ ] move new classes so they are not first level! -> will be fixe via #5272

Things for https://github.com/neos/neos-development-collection/pull/5042
- [x] add workspace name and content repository id and remove cs id in node aggregate
- [x] remove json serialize https://github.com/neos/neos-development-collection/issues/5051

**Comment by mhsdesign** [comment]
older notes just for reference :)


- [x] Userland should not need to operate on cs ids
  -> Events must operate on cs ids
- [x] getSubgraph arguments
    - [ ] ~WorkspaceName → internally resolved to cs id and will do lookup instantly (CACHE)~
     -> "refresh" mapping manually or implicit through handle? https://github.com/neos/neos-development-collection/pull/4943#discussion_r1548415771
    - [x] DimensionSpacePoint
    - [x] VisibilityConstraints
- [x] NodeFactory::mapNodeRowToNode  must accept WorkspaceName and ContentStreamId from outside.
    - [x] must accept ContentStreamId as parameter see https://github.com/neos/neos-development-collection/pull/4941
    - [x] must accept WorkspaceName as parameter
- [x] ~=> Extend SubgraphIdentity~
    - [ ] add workspaceName
    - [ ] add @internal annotation
       - [ ] and to its getters like `getIdentity` https://github.com/neos/neos-development-collection/pull/4678
- [ ] command handlers should still operate on cs ids ~via getSubgraphByIdentity - INTERNAL~
    - [x] by that both apis always pass the WorkspaceName
- [x] Node should know its
    - [x] ContentRepositoryId
    - [x] WorkspaceName
        - [x] NOT: ContentSubgraphIdentity.
        - [x] NOT: ContentStreamId
    - [x] DimensionSpacePoint it was fetched from
    - [x] VisibilityConstraints
       -> so it can be passed as single instance and eel helpers can fetch parents e.t.c in the same context
    - [x] OriginDimensionSpacePoint (as before)
- [ ] WorkspaceName::fromString() must be stricter without colons (so that we _could_ allow in the future for extension, e.g. WorkspaceName::detached(ContentStreamid $csId) (with an internal representation like “cs:<cs-id>”)

further todos from christian an me:

- [x] add workspaceName <-> contentStreamId table to content graph projection
- [ ] ~add workspaceName -> contentStreamId lookup to `ContentGraph::getSubgraph()`~ (with runtime cache in the `ContentGraph` – the same workspace will resolve to the same CS ID in one request, maybe reset runtime cache via `markStale()`)
- [ ] ~rewrite `ContentGraph::find*` queries to use workspaceName instead of contentStreamId~ (IMO it's totally fine to join the workspaceName <-> cs id table here for those queries. Alternatively we could add a dedicated lookup + runtime cache)
- [x] remove SubgraphIdentity

Afterwards we have to find out whether there are places that need to be able to override the workspace name -> cs id mapping for tests or CR constraints. If so we could either:
* Add a separate, internal, `ContentGraph::getSubgraphInternal()` – but that would be dangerous because it is part of the public interface (even if marked internal)
* Introduce a `ContentsubgraphFactoryInterface` that can be used via CR service
* Provide a way to hook into the runtime cache, e.g. `$contentGraph->dangerousSetContentStreamIdForWorkspaceNameFooBar(...)`
* Extract workspaceName<->cs id mapping to external service that can be replaced/hooked into

**Comment by kitsunet** [comment]
What is still missing for this now?

**Comment by mhsdesign** [comment]
Indeed most things are resolved with the merge of #5096 and the leftovers are either outdated or will be fixed via #5272
