### ISSUE TITLE
META: Current PR Dependency graph

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5057]
```mermaid
flowchart LR

  contentSubgraphIdentityRemoval

  removeNodeGetLabel -- depends --> templateAdjustments
  removeNodeGetNodeType -- depends --> templateAdjustments
  removeOldNodeAggregateId -- depends --> templateAdjustments
  removeOldNodeName -- depends --> templateAdjustments

  newContentRepositoryHooks -- depends --> reworkCRCatchUpMechanism
  reworkCRCatchUpMechanism <-- coordination --> preventMultipleCatchupRuns

  integrateCSProjectionInContentGraph <-- coordination --> integrateWsToCSMappingInContentGraph

  overhaulNodeTypeManager

  subgraph newUriSerializeableNodeAddress
    direction TB
    overHaulNodeUriBuilding
    restoreLinkingService
    adjustNeosUiToNewSerializationFormat
    refactorAllControllerToNewNodeAddress
  end

  improveNodeAddressSerialization -- depends --> newUriSerializeableNodeAddress

  removeLegacyNodeAddress -- depends --> newUriSerializeableNodeAddress

  repairAndTestCopyNodeCommand

  crPrivileges


%% wip things
  overhaulNodeTypeManager["overhaulNodeTypeManager 🚧"]
  restoreLinkingService["restoreLinkingService 🚧"]
  newContentRepositoryHooks["newContentRepositoryHooks 🚧"]
  reworkCRCatchUpMechanism["reworkCRCatchUpMechanism 🚧"]
  preventMultipleCatchupRuns["preventMultipleCatchupRuns 🚧"]

%% ideas and upcoming things
  crPrivileges["crPrivileges 💭"]
  repairAndTestCopyNodeCommand["repairAndTestCopyNodeCommand 💭"]
  templateAdjustments["templateAdjustments (fluid, fusion) 💭"]
```

- [ ] `integrateWsToCSMappingInContentGraph` https://github.com/neos/neos-development-collection/pull/5041
- [ ] `removeNodeGetNodeType` https://github.com/neos/neos-development-collection/pull/5021
- [ ] `repairAndTestCopyNodeCommand` https://github.com/neos/neos-development-collection/issues/5054
- [ ] `restoreLinkingService` https://github.com/neos/neos-development-collection/pull/4886
- [ ] `overHaulNodeUriBuilding ` https://github.com/neos/neos-development-collection/pull/4892
- [ ] `newContentRepositoryHooks` https://github.com/neos/neos-development-collection/pull/4995
- [ ] `reworkCRCatchUpMechanism` https://github.com/neos/neos-development-collection/pull/4988
- [ ] `preventMultipleCatchupRuns` https://github.com/neos/neos-development-collection/pull/4751
- [ ] `templateAdjustments` https://github.com/neos/neos-development-collection/issues/5023
- [ ] `contentSubgraphIdentityRemoval` https://github.com/neos/neos-development-collection/issues/5043

**Comment by mhsdesign** [comment]
The pr dependency graph here turns out to be too complex and no one used it besides me.
I put my current prs and how they block each other in a nested list with block icons and it might be simpler to maintain and overview:

https://neos-project.slack.com/docs/T04HF7TKV/F07133C4VNG
