### ISSUE TITLE
Setup / Migration

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#5245]
Epic for all Neos topics related to setting up / migrating Neos

- [x] FEATURE: High level cr:import / Read site:import #4448
- [ ] FEATURE: "Connect" new site entity to site node #4918
- [ ] BUG: migrateLegacyData fails while migrating from 8.3.4 #4504
- [x] Migrating old cr data with additional root nodes and their children #4895

**Comment by mhsdesign** [comment]
Another topic: https://github.com/neos/neos-development-collection/pull/5148#discussion_r1819758057 we also dont set the references in the legacy node migration apparently :O
