### ISSUE TITLE
META: CopyNodesRecursively vs Brain

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#5351]
Except the big known issues with `CopyNodesRecursively`

- 1.) [BUG: CopyNodesRecursively vs Tethered nodes](https://github.com/neos/neos-development-collection/issues/5350) 
- 2.) [BUG: CopyNodesRecursively vs Content Dimensions](https://github.com/neos/neos-development-collection/issues/5054) 

I think that once you start thinking about it, it does not stop seeing problem with it :D

- The `NodeSubtreeSnapshot` is NOT validated and taken for correct, imo it must not be possible for a user to do that accidentally with `CopyNodesRecursively`.

- On Rebase there is NO validation of the `$childNodes` to insert, we just turn the serialised `CopyNodesRecursively` directly back into `NodeAggregateWithNodeWasCreated` events, defeating the sense of replaying commands partially as we kinda copy events here:
  - This is problematic because the conditions when a node tree snapshot was created might have changes:
    - The target node that was referenced by a child node might be deleted,
    - A child nodes node type might have been adjusted and the new property schema is not validated
    - ... more?

- When copying nodes they will lose information about their subtreetags

**Comment by mhsdesign** [comment]
In todays weekly Christian, Denny, Paula, Basti and me discussed that we should probably have a  `Serialised` version of the command instead of adding the `NodeSubtreeSnapshot` to the API one.

Instead, the api one would contain:

```
NodeAggregateId $startNodeAggregateIdToCopy,
PropertyValuesToWrite $additionalPropertyValuesToWrite,
```

And we probably need to keep the `NodeAggregateIdMapping` on the api one for testing.

**Comment by mhsdesign** [comment]
List of missing test cases for copy, because well there are 2 so far :D

- [x] test that the tethered state of the initial node is ignored
- [ ] constraint test that the node is allowed to be inserted at that place (node type, parent exists, etc)
- [x] test that nested tethered nodes are copied WITH tethered state
  - [x] Even when its tethered directly in another thethered
- [x] test that tethered state of child nodes is redetermined as the parent node is now detached so a second level tethered node might not be tethered anymore, actually forbid that case
- [x] copying disabled nodes
- [ ] on rebase
  - [ ] assert that the referenced nodes still exist before creating them
- [ ] root nodes cannot be copied

....
