### ISSUE TITLE
EPIC: Followup new Neos.Workspace.UI

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-development-collection#5411]
# Planned features for 9.x after initial merge of the new module in 9.0:

- [ ] Force delete of workspaces with rebase of sub-workspaces and dropping unpublished changes
- [x] Move and update user stories for module from package to wiki or some other good place
- [ ] Define change base workspace and document it (originally introduced via https://github.com/neos/neos-development-collection/commit/e0b840802aaa554001c2f871790ccaa001d78f01)
- [ ] Assign roles to workspace (temporary removed with https://github.com/neos/neos-development-collection/commit/4aed44146bf8de69d6b0809c77b6e110d2409712)

## Additional open tasks

- [ ] Reimplement rebasing of the personal workspace
- [ ] Redirect to edit a change from the review mode
- [ ] Overhaul and improve publishing / discarding workflow
  - [ ] Load changes much faster
  - [ ] Improved UX for navigating between changes, sites (https://github.com/neos/neos-development-collection/issues/1070), dimensions
  - [ ] Improve handling of many changes (see also https://github.com/neos/neos-development-collection/issues/913)
  - [ ] Improved diff view

**Comment by tobiasgruber** [comment]
@Sebobo further ideas to improve the Workspace Module for editors (from my personal usage experience):

- directly link to the content pages in the breadcrumbs
<img width="1117" height="552" alt="Image" src="https://github.com/user-attachments/assets/a2a3a6e2-b038-4fec-8276-7ee4748bdeb7" />
- an actually rendered side-by-side view of the "before" and "after" versions
<img width="1161" height="590" alt="Image" src="https://github.com/user-attachments/assets/faf09104-0e92-486a-bdfb-9240deeac3b9" />
